### Dataset

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "WA_Fn-UseC_-Telco-Customer-Churn.csv"

df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "blastchar/telco-customer-churn",
  file_path,
)

df.head()

Using Colab cache for faster access to the 'telco-customer-churn' dataset.

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [ ]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import pandas as pd


num_cols = ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

cat_cols = ['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod']


# fixing total charges column that has floats as well as ' '
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce') # converts to NaN where errors come in converting
df['TotalCharges'].fillna(0, inplace=True)

df['Churn'].replace({"Yes": 1, "No": 0}, inplace=True)


for col in cat_cols:
    uniques = df[col].unique()
    print(col, uniques, len(uniques))

gender ['Female' 'Male'] 2
Partner ['Yes' 'No'] 2
Dependents ['No' 'Yes'] 2
PhoneService ['No' 'Yes'] 2
MultipleLines ['No phone service' 'No' 'Yes'] 3
InternetService ['DSL' 'Fiber optic' 'No'] 3
OnlineSecurity ['No' 'Yes' 'No internet service'] 3
OnlineBackup ['Yes' 'No' 'No internet service'] 3
DeviceProtection ['No' 'Yes' 'No internet service'] 3
TechSupport ['No' 'Yes' 'No internet service'] 3
StreamingTV ['No' 'Yes' 'No internet service'] 3
StreamingMovies ['No' 'Yes' 'No internet service'] 3
Contract ['Month-to-month' 'One year' 'Two year'] 3
PaperlessBilling ['Yes' 'No'] 2
PaymentMethod ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)'] 4

/tmp/ipykernel_3238/1721995095.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TotalCharges'].fillna(0, inplace=True)
/tmp/ipykernel_3238/1721995095.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Churn'].replace({"Yes": 1, "No": 0}, inplace=True)
/tmp/ipykernel_3238/1721995095.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Churn'].replace({"Yes": 1, "No": 0}, inplace=True)

### Logistic

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(), cat_cols)
    ]
)

logistic_pipe = Pipeline([
    ('preprocess', preprocessor),
    ('model', LogisticRegression(random_state=42, class_weight='balanced'))
])

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop(['Churn', 'customerID'], axis=1)
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
# stratify makes sure that imbalanced classification sets are not made, important in classification

print(len(X_train), len(X_test))

5634 1409

In [ ]:
logistic_pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat', OneHotEncoder(),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', random_state=42))])

In [ ]:
logistic_pipe.score(X_test, y_test)

0.7381121362668559

In [ ]:
logistic_param_grid = {
    'model__C': [0.001, 0.01, 0.1, 1, 10, 100]
}

from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(logistic_pipe, logistic_param_grid, cv=5, scoring='f1', n_jobs=-1)
grid_search.fit(X_train, y_train)

grid_search.best_params_

{'model__C': 0.1}

In [ ]:
logistic_pipe.score(X_test, y_test)

0.7381121362668559

### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

random_forest_pipe = Pipeline([
    ('preprocess', preprocessor),
    ('model', RandomForestClassifier(class_weight='balanced', random_state=42))
])

random_forest_param_grid = {
    'model__n_estimators': [50, 100, 150],
    'model__max_depth': [None, 10, 20],
    'model__min_samples_split': [2, 5, 8]
}

grid_search = GridSearchCV(random_forest_pipe, random_forest_param_grid, cv=5, scoring='f1', n_jobs=-1)
grid_search.fit(X_train, y_train)

grid_search.best_params_

{'model__max_depth': 10,
 'model__min_samples_split': 8,
 'model__n_estimators': 50}

In [ ]:
grid_search.score(X_test, y_test)

0.6136363636363636

### Saving

In [ ]:
import joblib

joblib.dump(logistic_pipe, 'logistic_pipe.joblib')
joblib.dump(random_forest_pipe, 'random_forest_pipe.joblib')

['random_forest_pipe.joblib']